on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: 2.1.6

      - run: deno task build

      - run: find

      - run: cd ~/.cache/deno && find
