on:
  push:
  workflow_dispatch:
    inputs:
      deno_version:
        type: string
        required: false
        default: 2.1.6

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno_version }}

      - run: deno task build

      - run: find

      - run: cd ~/.cache/deno && find

      - run: mv deno.json.vendor deno.json

      - run: deno task build
